# Site settings
title: Graces Games
author: Graces Games
email: contact@gracesgames.com
url: https://GracesGames.github.io
description: "Game Development and Tools"
keywords: "graces, games, graces games, development, tools, unity, unreal"
skills: "Game Development and Tools"
meta_author: Graces Games

google_analytics: UA-99027396-2

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6ead3a #80B3FF
  primary-rgb: "206,204,206" #"128,179,255"
  secondary: 222022 #FD6E8A
  secondary-dark: 090908 #A2122F

# Footer settings
footer:
  copyright: Graces Games
  social: GET IN TOUCH

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: fa fa-fw fa-envelope # Email
    url: mailto:contact@gracesgames.com
  - title: fab fa-fw fa-discord
    url: https://discord.gg/DBwFAES
  - title: fa fa-fw fa-bolt # Game Jolt
    url: https://gamejolt.com/@GracesGames#close

# Build settings
markdown: kramdown
permalink: /project/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
